### ISSUE TITLE
Tracklist is not displayed

### ISSUE THREAD

**Issue by catalin-florescu** [adlawson/mixcloud-tracklist#33] opened 2017-08-10 07:30 UTC
Tracklist is no more displayed, but in player song appears. Does API changed?

**Comment by zygisber** [comment] 2017-08-10 07:40
function fetchData(location, fn) {
    request({
        "uri": "/player/details",
        "baseUrl": location.protocol + "//" + location.hostname,
        "qs": { "key": location.pathname },
        "json": true
    }, function (error, response, data) {
        if (!error && response.statusCode === 200 &&
data.cloudcast.sections.length > 0) {
            fn(insertTrackNumber(data));
        } else {
            console.error(error);
        }
    });
}

Now request returns response.statusCode = 200 everytime.

**Comment by catalin-florescu** [comment] 2017-08-10 07:49
@zygisber I'm not familiar with JS, can you explain what to do?

**Comment by adlawson** [comment] 2017-08-10 09:34
Duplicate of #32

**Closed as completed by adlawson** 2017-08-10 09:34 UTC
